#! /usr/bin/env sh

# File to test
EXP_SCRIPT="hicking2.py"

# Text colors
COLOR_REST="$(tput sgr0)"
COLOR_RED="$(tput setaf 1)"
COLOR_GREEN="$(tput setaf 2)"

# Test counters
NB_TEST_OK=0
NB_TEST_TOTAL=0

##################################################
# Check if python is available
##################################################
pyapp=`which python`
if [ "${pyapp:0:1}" == "/" ]
then
    python --version
else
    printf "Python not found\n"
    exit
fi

##################################################
# Check if the script is given
##################################################
GIVEN_SCRIPT=""
if [ $# -eq 1 ]
then
    GIVEN_SCRIPT="${1}"
else
    printf "Give the script name in command line\n"
    exit
fi

##################################################
# Check if the script is correct
##################################################
if [ "${GIVEN_SCRIPT}" != "${EXP_SCRIPT}" ]
then
    printf "Script name is not correct, it should be: ${GIVEN_SCRIPT}\n"
    exit
fi

##################################################
# Check if the given script exists
##################################################
if [ ! -f "${EXP_SCRIPT}" ]
then
    printf "File not found: ${EXP_SCRIPT}\n"
    exit
fi


##################################################
# Test function
##################################################
run_test () {
    TEST_NAME=$1
    TEST_NUM=$2
    TEST_PARAM=$3
    TEST_IN=.test/${TEST_NUM}.in
    TEST_EXP=.test/${TEST_NUM}.exp
    TEST_OUT=".test/${TEST_NUM}_test.out"
    TEST_DIFF=".test/${TEST_NUM}_test.diff"
    python ${EXP_SCRIPT} ${TEST_PARAM} > ${TEST_OUT}
    NB_LINES=`cat ${TEST_OUT} | wc -c`
    if [ ${NB_LINES} -eq 0 ]
    then
        printf "\n"
        printf "${TEST_NUM} ${COLOR_RED}\xE2\x9C\x97${COLOR_REST} ${TEST_NAME}\n"
        printf "Your script prints nothing\n"
    fi
    diff ${TEST_EXP} ${TEST_OUT} > ${TEST_DIFF}
    NB_DIFF=`cat ${TEST_DIFF} | wc -l`
    NB_TEST_TOTAL=$((NB_TEST_TOTAL+1))
    if [ ${NB_DIFF} -eq 0 ]
    then
        printf "${TEST_NUM} ${COLOR_GREEN}\xE2\x9C\x94${COLOR_REST} ${TEST_NAME}\n"
        rm ${TEST_OUT}
        rm ${TEST_DIFF}
        NB_TEST_OK=$((NB_TEST_OK+1))
    else
        printf "\n"
        printf "${TEST_NUM} ${COLOR_RED}\xE2\x9C\x97${COLOR_REST} ${TEST_NAME}\n"
        printf "${COLOR_GREEN}Expected${COLOR_REST}\n"
        grep "<" ${TEST_DIFF}
        printf "${COLOR_RED}Given${COLOR_REST}\n"
        grep ">" ${TEST_DIFF}
        printf "\n"
    fi
}

##################################################
# Run tests
##################################################
run_test "Hicking 01 - 1" "01" ".test/01.in"
run_test "Hicking 02 - 2" "02" ".test/02.in"
run_test "Hicking 03 - 3" "03" ".test/03.in"
run_test "Hicking 04 - 6" "04" ".test/04.in"
run_test "Hicking 05 - 13" "05" ".test/05.in"
run_test "Hicking 06 - 5" "06" ".test/06.in"
run_test "Hicking 07 - 9" "07" ".test/07.in" 
run_test "Hicking 08 - 16" "08" ".test/08.in"
run_test "Hicking 09 - 35" "09" ".test/09.in"
run_test "Hicking 10 - 82" "10" ".test/10.in"
run_test "Hicking 11 - 1162" "11" ".test/11.in"

##################################################
# Print Summary
##################################################
if [ ${NB_TEST_OK} -eq ${NB_TEST_TOTAL} ]
then
    printf "Validated: ${COLOR_GREEN}${NB_TEST_OK}/${NB_TEST_TOTAL}${COLOR_REST}\n"
else
    printf "Validated: ${COLOR_RED}${NB_TEST_OK}/${NB_TEST_TOTAL}${COLOR_REST}\n"
fi
